version: '3'
services:
  db:
    image:  mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mjjs
      MYSQL_USER: mjjsuser
      MYSQL_PASSWORD: mjjspassword
    volumes:
      - /var/lib/mysql
      - ./mjjs.sql:/docker-entrypoint-initdb.d/data.sql  

    ports:
      - "3306:3306"
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: mjjsuser
      PMA_PORT: 3306
      MYSQL_PASSWORD: mjjspassword
    links:
      - db
    networks:
      - my_network
    volumes:
      - ./logs:/var/log/apache2  



networks:
  my_network:
    driver: bridge
